faq data protection 121 and fsp
global-121/manual pull request #54
Opened 2024-12-19 11:07 UTC by cassandradamico

adding content in data protection
editing some of the content to precise users resp
adding content for FSP data sharing

2024-12-19 12:16 UTC, emily-walkin requested changes

2024-12-19 12:16 UTC, emily-walkin commented on docs/faq/data-protection.md
> +??? "8. Who process the data?"
typo: Who processes the data?

2024-12-19 12:16 UTC, emily-walkin commented on docs/faq/data-protection.md
> +??? "9. What are my responsabilities as 121 user?"
typo: **responsibilities** as **a** 121 user?

2024-12-19 12:16 UTC, emily-walkin commented on docs/faq/data-protection.md
> +      - Confirm the password in the Reenter Password box, and then select OK.
Not sure how the formatting looks here? How it shows up here this all looks like one list, but actually rows above this comment (123-126 are related to protecting workbooks in excel, and below are an overview of other recommendations.

2024-12-19 14:10 UTC, emily-walkin approved these changes

2024-12-19 14:19 UTC, emily-walkin requested changes

2024-12-19 14:19 UTC, emily-walkin commented on docs/faq/data-protection.md
> +??? "8. Who process the data?"
I still see the same problem here?

2024-12-19 14:19 UTC, emily-walkin commented on docs/faq/data-protection.md
> +??? "9. What are my responsabilities as 121 user?"
Still see the same problem here?

2024-12-19 14:19 UTC, emily-walkin commented on docs/faq/data-protection.md
> +      - Confirm the password in the Reenter Password box, and then select OK.
Still see the same problem here?

2025-01-27 12:20 UTC, tijsziere approved these changes

2025-01-27 12:21 UTC, merged